chore(ci): Add linux arm build back (#8406)

diff --git a/.github/workflows/publish-core.yml b/.github/workflows/publish-core.yml
--- a/.github/workflows/publish-core.yml
+++ b/.github/workflows/publish-core.yml
@@ -47,25 +47,24 @@ jobs:
               cp ./bindings/target/release/swc .
             target: x86_64-pc-windows-msvc
           - host: windows-latest
+            # use npm to run test, because of corepack link the yarn with x64 Node.js
             build: |
               export DISABLE_PLUGIN_E2E_TESTS=true
               export CARGO_PROFILE_RELEASE_LTO=false
               cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --target i686-pc-windows-msvc
               cp bindings/target/i686-pc-windows-msvc/release/swc .
-              yarn build --target i686-pc-windows-msvc --cargo-flags="--no-default-features" --features swc_v1
-              yarn test
+              yarn build --target i686-pc-windows-msvc --no-default-features --features swc_v1
+              npm run test
             target: i686-pc-windows-msvc
           - host: ubuntu-latest
             target: x86_64-unknown-linux-gnu
             docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
             build: >-
               set -e &&
-              yarn policies set-version 1.22.19 && 
               unset CC_x86_64_unknown_linux_gnu && unset CC && RUSTFLAGS='-C target-feature=+sse2' cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --features plugin &&
               rm -rf bindings/target/target/x86_64-unknown-linux-gnu/release/.cargo-lock &&
               cp bindings/target/x86_64-unknown-linux-gnu/release/swc . && chmod +x ./swc &&
-              yarn build --target x86_64-unknown-linux-gnu &&
-              strip swc.linux-x64-gnu.node
+              yarn build --target x86_64-unknown-linux-gnu
           - host: ubuntu-latest
             target: x86_64-unknown-linux-musl
             # musl build is slow, let's disable the LTO
@@ -76,8 +75,7 @@ jobs:
               RUSTFLAGS='-C target-feature=+sse2' cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --features plugin &&
               rm -rf target/release/.cargo-lock &&
               cp bindings/target/release/swc . && chmod +x ./swc &&
-              RUSTFLAGS='-C target-feature=+sse2 -C target-feature=-crt-static' yarn build &&
-              llvm-strip -x swc.linux-x64-musl.node
+              RUSTFLAGS='-C target-feature=+sse2 -C target-feature=-crt-static' yarn build
           - host: macos-latest
             target: aarch64-apple-darwin
             build: |
@@ -89,33 +87,25 @@ jobs:
               cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --features plugin --target=aarch64-apple-darwin
               cp ./bindings/target/aarch64-apple-darwin/release/swc .
               chmod +x ./swc
-              yarn build --target=aarch64-apple-darwin
-              strip -x *.node
+              yarn build --target aarch64-apple-darwin
           - host: ubuntu-latest
             target: aarch64-unknown-linux-gnu
             docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
             build: >-
               set -e &&
-              yarn policies set-version 1.22.19 && 
               export JEMALLOC_SYS_WITH_LG_PAGE=16 &&
               rustup target add aarch64-unknown-linux-gnu &&
               RUSTFLAGS='' cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --features plugin --target aarch64-unknown-linux-gnu &&
               cp ./bindings/target/aarch64-unknown-linux-gnu/release/swc . && chmod +x ./swc &&
               export CC_aarch64_unknown_linux_gnu=/usr/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-gcc &&
-              yarn build --target aarch64-unknown-linux-gnu &&
-              llvm-strip -x swc.linux-arm64-gnu.node
-          # - host: ubuntu-latest
-          #   target: armv7-unknown-linux-gnueabihf
-          #   setup: |
-          #     sudo apt-get update
-          #     sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
-          #   # Use napi to build cli binary here to use zig as linker
-          #   build: |
-          #     export DISABLE_PLUGIN_E2E_TESTS=true
-          #     yarn napi build --bin swc --release --target armv7-unknown-linux-gnueabihf --cargo-cwd ./bindings/swc_cli --cargo-name swc --zig --zig-link-only
-          #     chmod +x ./swc
-          #     yarn build --target armv7-unknown-linux-gnueabihf --cargo-flags='--no-default-features --features swc_v1'
-          #     arm-linux-gnueabihf-strip swc.linux-arm-gnueabihf.node
+              yarn build --target aarch64-unknown-linux-gnu
+          - host: ubuntu-latest
+            target: armv7-unknown-linux-gnueabihf
+            build: |
+              export DISABLE_PLUGIN_E2E_TESTS=true
+              yarn napi build --bin swc --release --target armv7-unknown-linux-gnueabihf --manifest-path ./bindings/swc_cli/Cargo.toml -x --target-dir ../release -o .
+              chmod +x ./swc
+              yarn build --target armv7-unknown-linux-gnueabihf --no-default-features --features swc_v1 --use-napi-cross
           - host: ubuntu-latest
             target: aarch64-unknown-linux-musl
             downloadTarget: aarch64-unknown-linux-musl
@@ -127,8 +117,7 @@ jobs:
               RUSTFLAGS='-C target-feature=+crt-static -C link-arg=-lgcc' cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --features plugin --target aarch64-unknown-linux-musl &&
               rm -rf target/release/.cargo-lock &&
               cp bindings/target/aarch64-unknown-linux-musl/release/swc . && chmod +x ./swc &&
-              env RUSTFLAGS='-C target-feature=-crt-static' yarn build --target=aarch64-unknown-linux-musl &&
-              /aarch64-linux-musl-cross/bin/aarch64-linux-musl-strip swc.linux-arm64-musl.node
+              env RUSTFLAGS='-C target-feature=-crt-static' yarn build --target=aarch64-unknown-linux-musl
           - host: windows-latest
             target: aarch64-pc-windows-msvc
             # Disable `LTO` and increase `codegen-units` to avoid llvm `OOM` on GitHub Actions.
@@ -138,65 +127,69 @@ jobs:
               export CARGO_PROFILE_RELEASE_LTO=false
               cargo build --manifest-path ./bindings/swc_cli/Cargo.toml --release --target aarch64-pc-windows-msvc
               cp bindings/target/aarch64-pc-windows-msvc/release/swc.exe .
-              yarn build --target aarch64-pc-windows-msvc --cargo-flags='--no-default-features --features swc_v1'
-    name: stable - ${{ matrix.settings.target }} - node@18
+              yarn build --target aarch64-pc-windows-msvc --no-default-features --features swc_v1
+    name: stable - ${{ matrix.settings.target }} - node@20
     runs-on: ${{ matrix.settings.host }}
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+      - name: Corepack
+        shell: bash
+        run: corepack enable
       - name: Setup node x64
-        uses: actions/setup-node@v3
-        if: matrix.settings.target != 'i686-pc-windows-msvc'
+        uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
           cache: yarn
           architecture: x64
-      - name: Setup node x86
-        uses: actions/setup-node@v3
-        if: matrix.settings.target == 'i686-pc-windows-msvc'
-        with:
-          node-version: 18
-          cache: yarn
-          architecture: x86
+      - name: Output toolchain
+        id: toolchain
+        shell: bash
+        run: echo "version=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"
       - name: Install
-        uses: actions-rs/toolchain@v1
+        uses: dtolnay/rust-toolchain@stable
         if: ${{ !matrix.settings.docker }}
         with:
-          profile: minimal
-          override: true
-          target: ${{ matrix.settings.target }}
+          targets: ${{ matrix.settings.target }}
+          toolchain: ${{ steps.toolchain.outputs.version }}
       - uses: goto-bus-stop/setup-zig@v2
         if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' }}
         with:
-          version: 0.10.1
-      - name: Install node dependencies
-        shell: bash
-        run: |
-          yarn
+          version: 0.11.0
       - name: Cache cargo registry
         uses: actions/cache@v3
         with:
           path: ~/.cargo/registry
-          key: ${{ matrix.settings.target }}-node@18-cargo-registry-trimmed
+          key: ${{ matrix.settings.target }}-node@20-cargo-registry-trimmed
       - name: Cache cargo index
         uses: actions/cache@v3
         with:
           path: ~/.cargo/git
-          key: ${{ matrix.settings.target }}-node@18-cargo-index-trimmed
-
+          key: ${{ matrix.settings.target }}-node@20-cargo-index-trimmed
         if: ${{ matrix.settings.docker }}
       - name: Setup toolchain
         run: ${{ matrix.settings.setup }}
         if: ${{ matrix.settings.setup }}
         shell: bash
+      # use x64 Node.js to install dependencies because of ia32 version will fail with `Error: Couldn't allocate enough memory`
+      - name: Setup install target x86
+        if: matrix.settings.target == 'i686-pc-windows-msvc'
+        run: yarn config set supportedArchitectures.cpu "ia32"
+        shell: bash
       - name: Install dependencies
+        # run corepack enable again
+        # because on Windows, yarn will use `cmd` to run `yarn install`
+        shell: bash
         run: |
-          # Workaround for
-          # https://github.com/yarnpkg/yarn/issues/9015#issuecomment-1831229617
-          yarn policies set-version 1.22.19
-
-          yarn install --ignore-scripts --registry https://registry.npmjs.org --network-timeout 300000
+          corepack enable
+          yarn install
           curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
           echo '/usr/local/cargo/bin' >> $GITHUB_PATH
+      - name: Setup node x86
+        uses: actions/setup-node@v4
+        if: matrix.settings.target == 'i686-pc-windows-msvc'
+        with:
+          node-version: 20
+          architecture: x86
       - name: Build in docker
         uses: addnab/docker-run-action@v3
         if: ${{ matrix.settings.docker }}
@@ -204,7 +197,8 @@ jobs:
           image: ${{ matrix.settings.docker }}
           options: -v ${{ env.HOME }}/.cargo/git:/root/.cargo/git -v ${{ env.HOME }}/.cargo/registry:/root/.cargo/registry -v ${{ github.workspace }}:/build -w /build
           run: >-
-            yarn global add wasm-pack &&
+            corepack enable &&
+            npm i -g wasm-pack &&
             ${{ matrix.settings.build }}
       - name: Build
         if: ${{ !matrix.settings.docker }}
@@ -228,14 +222,16 @@ jobs:
         settings:
           - host: windows-latest
             target: x86_64-pc-windows-msvc
+          - host: macos-latest
+            target: x86_64-apple-darwin
         node:
-          - "16"
           - "18"
+          - "20"
     runs-on: ${{ matrix.settings.host }}
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - name: Setup node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node }}
           cache: yarn
@@ -262,23 +258,20 @@ jobs:
       fail-fast: false
       matrix:
         node:
-          - "16"
           - "18"
+          - "20"
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+      - name: Corepack
+        run: corepack enable
       - name: Setup node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node }}
           cache: yarn
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: npm-cache-test-linux-x64-gnu-${{ matrix.node }}
       - name: Install dependencies
-        run: yarn install --ignore-scripts --registry https://registry.npmjs.org --network-timeout 300000
+        run: yarn install
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
@@ -300,18 +293,20 @@ jobs:
       fail-fast: false
       matrix:
         node:
-          - "16"
           - "18"
+          - "20"
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - name: Setup node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node }}
           cache: yarn
       - name: Install dependencies
-        run: yarn install --ignore-scripts --registry https://registry.npmjs.org --network-timeout 300000
+        run: |
+          yarn config set supportedArchitectures.libc "musl"
+          yarn install
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
@@ -326,12 +321,14 @@ jobs:
         run: docker run --rm -v $(pwd):/swc -w /swc node:${{ matrix.node }}-alpine env DISABLE_PLUGIN_E2E_TESTS=true yarn test
   test-linux-aarch64-musl-binding:
     if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/ci') }}
-    name: Test bindings on aarch64-unknown-linux-musl - node@${{ matrix.node }}
+    name: Test bindings on aarch64-unknown-linux-musl - node@lts
     needs:
       - build
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+      - name: Corepack
+        run: corepack enable
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
@@ -340,13 +337,11 @@ jobs:
       - name: List packages
         run: ls -R .
         shell: bash
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: npm-cache-test-linux-aarch64-musl-${{ matrix.node }}
       - name: Install dependencies
-        run: yarn install --ignore-scripts --ignore-platform --registry https://registry.npmjs.org --network-timeout 300000
+        run: |
+          yarn config set supportedArchitectures.cpu "arm64"
+          yarn config set supportedArchitectures.libc "musl"
+          yarn install
       - name: Build TypeScript
         run: yarn build:ts
       - name: Set up QEMU
@@ -362,53 +357,51 @@ jobs:
           run: >-
             set -e &&
             DISABLE_PLUGIN_E2E_TESTS=true yarn test
-  # https://github.com/ziglang/zig/issues/16152
-  #
-  # test-linux-arm-gnueabihf-binding:
-  #   if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/ci') }}
-  #   name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
-  #   needs:
-  #     - build
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       node:
-  #         - "16"
-  #         - "18"
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - name: Download artifacts
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: bindings-armv7-unknown-linux-gnueabihf
-  #         path: .
-  #     - name: List packages
-  #       run: ls -R .
-  #       shell: bash
-  #     - name: Cache NPM dependencies
-  #       uses: actions/cache@v3
-  #       with:
-  #         path: node_modules
-  #         key: npm-cache-test-linux-arm-gnueabihf-${{ matrix.node }}
-  #     - name: Install dependencies
-  #       run: yarn install --ignore-scripts --ignore-platform --registry https://registry.npmjs.org --network-timeout 300000
-  #     - name: Build TypeScript
-  #       run: yarn build:ts
-  #     - name: Set up QEMU
-  #       uses: docker/setup-qemu-action@v2
-  #       with:
-  #         platforms: arm
-  #     - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-  #     - name: Setup and run tests
-  #       uses: addnab/docker-run-action@v3
-  #       with:
-  #         image: node:${{ matrix.node }}-bullseye-slim
-  #         options: "--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build"
-  #         run: >-
-  #           set -e &&
-  #           DISABLE_PLUGIN_E2E_TESTS=true yarn test &&
-  #           ls -la
+
+  test-linux-arm-gnueabihf-binding:
+    if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/ci') }}
+    name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
+    needs:
+      - build
+    strategy:
+      fail-fast: false
+      matrix:
+        node:
+          - "18"
+          - "20"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Corepack
+        run: corepack enable
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: bindings-armv7-unknown-linux-gnueabihf
+          path: .
+      - name: List packages
+        run: ls -R .
+        shell: bash
+      - name: Install dependencies
+        run: |
+          yarn config set supportedArchitectures.cpu "arm"
+          yarn install
+      - name: Build TypeScript
+        run: yarn build:ts
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+        with:
+          platforms: arm
+      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+      - name: Setup and run tests
+        uses: addnab/docker-run-action@v3
+        with:
+          image: node:${{ matrix.node }}-slim
+          options: "--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build"
+          run: >-
+            set -e &&
+            DISABLE_PLUGIN_E2E_TESTS=true yarn test &&
+            ls -la
   publish:
     if: ${{ startsWith(github.ref, 'refs/tags/v') }}
 
@@ -417,14 +410,17 @@ jobs:
     needs:
       - test-linux-x64-gnu-binding
       - test-linux-x64-musl-binding
-      # - test-linux-arm-gnueabihf-binding
+      - test-linux-arm-gnueabihf-binding
       - test-macOS-windows-binding
       - test-linux-aarch64-musl-binding
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+
+      - name: Corepack
+        run: corepack enable
 
       - name: Setup node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: 18
           cache: yarn
@@ -440,7 +436,7 @@ jobs:
         run: echo "NPM_TAG=nightly" >> $GITHUB_ENV
 
       - name: Install dependencies
-        run: yarn install --ignore-scripts --registry https://registry.npmjs.org --network-timeout 300000
+        run: yarn install
 
       - name: Download all artifacts
         uses: actions/download-artifact@v3
@@ -490,7 +486,10 @@ jobs:
     name: Build - wasm for node.js
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+
+      - name: Corepack
+        run: corepack enable
 
       - name: Tag npm release (default, latest)
         run: echo "NPM_TAG=latest" >> $GITHUB_ENV
@@ -500,9 +499,9 @@ jobs:
         run: echo "NPM_TAG=nightly" >> $GITHUB_ENV
 
       - name: Setup node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: 16
+          node-version: 20
 
       - name: Cache
         uses: actions/cache@v3
@@ -539,7 +538,10 @@ jobs:
     name: Build - wasm for web
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+
+      - name: Corepack
+        run: corepack enable
 
       - name: Tag npm release (default, latest)
         run: echo "NPM_TAG=latest" >> $GITHUB_ENV
@@ -549,9 +551,9 @@ jobs:
         run: echo "NPM_TAG=nightly" >> $GITHUB_ENV
 
       - name: Setup node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
-          node-version: 16
+          node-version: 20
 
       - name: Cache
         uses: actions/cache@v3
